services:
  linkshort:
    build:
      context: .
      dockerfile: Dockerfile
    image: linkshort
    container_name: linkshort
    ports:
      - "8000:8000"
    volumes:
      - ./links.db:/app/links.db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Dhaka
    restart: unless-stopped
